export const texts = {
  fr: {
    title: "Présentation",
    aboutMeTitle: "À propos de moi",
    aboutMeText: `Bonjour, je m’appelle Maël LLADO. Je suis actuellement étudiant à l’école privée Ynov Campus Bordeaux, après avoir obtenu mon Baccalauréat Professionnel SN (Systèmes Numériques), option RISC, avec la mention Très Bien, au lycée polyvalent Jean-Monnet de Libourne.`,
    parcoursTitle: "Parcours et expériences",
    parcoursText: `Passionné d’informatique depuis le collège...`,
    projetsTitle: "Projets personnels",
    projetsText: `En autodidacte, j’ai appris le Python...`,
    objectifsTitle: "Objectifs",
    objectifsText: `Mon objectif est de continuer à apprendre...`,
    fichiersTitle: "Fichiers joints",
    cvBtn: "Mon CV",
    portfolioBtn: "Mon Portfolio",
  },
  en: {
    title: "Presentation",
    aboutMeTitle: "About Me",
    aboutMeText: `Hello, my name is Maël LLADO. I am currently a student at the private school Ynov Campus Bordeaux, after obtaining my Professional Baccalaureate in SN (Digital Systems), RISC option, with Highest Honors, at the Jean-Monnet Polyvalent High School in Libourne.`,
    parcoursTitle: "Background & Experience",
    parcoursText: `Passionate about IT since middle school...`,
    projetsTitle: "Personal Projects",
    projetsText: `As a self-taught developer, I learned Python...`,
    objectifsTitle: "Goals",
    objectifsText: `My goal is to keep learning and gaining experience...`,
    fichiersTitle: "Attached Files",
    cvBtn: "My CV",
    portfolioBtn: "My Portfolio",
  },
};
