export const texts = {
  fr: {
    titleHome: "Présentation",

    aboutMeTitle: "À propos de moi",
    aboutMeText: `Bonjour, je m’appelle <strong>Maël LLADO</strong>. Je suis actuellement étudiant à l’école privée <strong>Ynov Campus Bordeaux</strong>, après avoir obtenu mon <strong>Baccalauréat Professionnel SN (Systèmes Numériques), option RISC</strong>, avec la <strong>mention Très Bien</strong>, au lycée polyvalent Jean-Monnet de Libourne.`,
    parcoursTitle: "Parcours et expériences",
    parcoursText: `Passionné d’informatique depuis le collège, j’ai orienté mon parcours vers la programmation. Lors de mes stages chez <strong>Snark Factory</strong>, j’ai découvert le développement web et appris le <strong>HTML, CSS, SCSS</strong> et le <strong>JavaScript</strong>, en réalisant plusieurs sites en <strong>Vue.js</strong>.`,
    parcoursTextSeconde: `J’ai également effectué d’autres stages en maintenance informatique et en boutique spécialisée, ce qui m’a permis d’élargir mes compétences.`,
    projetsTitle: "Projets personnels",
    projetsText: `En autodidacte, j’ai appris le <strong>Python</strong> et développé un de mes plus gros projets : un logiciel de <strong>reconnaissance faciale</strong>, présenté à l’oral de mon Bac. Ce projet m’a permis d’apprendre à utiliser <strong>GitHub</strong> et à structurer mon code comme un vrai développeur.`,
    projetsTextSeconde: `J’ai aussi expérimenté la <strong>programmation de jeux vidéo</strong> avec <strong>Unreal Engine 5</strong>, par curiosité et pour élargir mes connaissances.`,
    objectifsTitle: "Objectifs",
    objectifsText: `Mon objectif est de continuer à apprendre et à acquérir de l’expérience dans différents domaines de l’informatique. Je souhaite devenir <strong>polyvalent</strong>, aussi bien en <strong>développement web</strong>, <strong>full-stack</strong> qu’en <strong>programmation de jeux vidéo</strong>, qui sont les sujets qui m’intéressent le plus.`,
    objectifsTextSeconde: `J’ai également une première expérience en <strong>cybersécurité</strong>, grâce à mes trois années de Bac Pro SN RISC, à ma participation à des <strong>CTF</strong> et à mes recherches personnelles. Curieux et motivé, j’aime relever de nouveaux défis et je souhaite évoluer vers un métier passionnant dans le développement informatique.`,
    fichiersTitle: "Fichiers joints",
    fichiersText: `Vous pouvez retrouver ici mon CV et mon portfolio pour en savoir plus sur mon parcours et mes projets.`,
    cvBtn: "Mon CV",
    portfolioBtn: "Mon Portfolio",

    titleContact: `Contacts`,

    textContact: `Toujours ouvert à discuter, que ce soit pour des projets professionnels, personnels ou pour des offres d’emploi 👋 !`,

    titleProject: `Mes Projets`,

    titleProjectP1: `Projet_Red: Eldoria`,
    textProjectP1: `Ce projet a été créé dans le cadre de mes études à Ynov Campus lors de ma première année (B1). Il a été réalisé en une semaine en Golang. On nous a demandé de créer un jeu CLI, c’est-à-dire en ligne de commande dans le terminal.`,
    titleGithubP1: `Github`,
    textGithubP1: `Pour ce Projet nous etions 3 et notre projet est entierement disponible sur Gihub`,
    descriptionTextP1: `Eldoria est un jeu d'aventure textuel où vous incarnez un explorateur qui découvre le village d'Ynovia. Rencontrez Emeryn, le guide du village, et percez les mystères qui entourent ce lieu magique. Découvrez un portail vers un autre monde, mais attention aux monstres qui rôdent... et au redoutable boss Maximor ! Ce jeu est en ligne de commande dans le Terminal (CLI), mais intègre une particularité unique : une map interactive pour un jeu plus agréable à jouer.`,
    textReadMe: `Voici un extrait du Read.me`,
    titleLanguage: `Langue`,
    linkTextGithub: `Voir le Projet sur Github`,

    textProjectP2: `J’ai eu 4 semaines pour coder un logiciel en Python. J’ai dû réaliser plusieurs versions de mon code : une pour les photos, une autre pour les vidéos et une dernière pour la vidéo en direct via la webcam.`,
    titleGithubP2: `Personnel: GitHub`,
    textGithubP2: `Ce projet est un projet personnel que j’ai mené afin de gagner des points bonus pour mon bac Profesionnel SN Option RISC `,
    descriptionTextP2: `Notre projet porte sur la reconnaissance faciale. Nous codons en Python 3 sur Visual Studio Code. Notre projet consiste à reconnaître les visages présents sur une photo ou sur une vidéo, puis à les comparer à une base de données comportant plusieurs visages dans plusieurs dossiers différents. L'objectif est de déterminer si la personne est connue de la base de données ou si elle est inconnue. Si le visage est reconnu, le logiciel doit simplement afficher le nom de cette personne sur l'image. Ce logiciel est intéressant car il peut être utilisé dans un dispositif de sécurité, dans diverses situations ou comme un "portier" dans un lieu où l'on pourrait installer ce dispositif devant une porte ou un portail. S'il reconnaît la personne, la porte ou le portail se déverrouille, et inversement. Cela constitue l'aspect utile de notre projet, qui répond à de vrais problèmes et besoins en matière de sécurité.`,

    textProjectP3: `J'ai participé au CTF 2025 sur le site Root Me, organisé par cette même plateforme.`,
    titleGithubP3: `Ecole SN`,
    textGithubP3: `Ce projet nous a été proposé par notre professeur de Sciences Numériques afin de nous entraîner à la sécurité informatique et au hacking éthique.`,
    descriptionTextP3_1: `CTF Entrainement et Realisation (Programmation, Web)`,
    descriptionTextP3_2: `Le CTF (Capture The Flag) est une compétition nationale de Cybersécurité où les participants s’affrontent pour résoudre des énigmes et des problèmes de sécurité informatique.`,
    descriptionTextP3_3: `Le but ultime est de « capturer le drapeau », qui est généralement un code secret ou un fichier spécifique caché dans un système informatique vulnérable.`,
    descriptionTextP3_4: `Les CTF sont des environnements sécurisés qui permettent aux professionnels et aux étudiants en sécurité informatique d’apprendre, de pratiquer et de développer leurs compétences tout en s’amusant.`,

    textProjectP5: `One Piece DLE est un projet de fan game basé sur l'univers de One Piece. Le but de ce jeux est de trouver un personnage precis dans l'univers de one piece comme un geoguessr pour les personnage.`,
    textGithubP5: `Projet a etais fait personnelement en dehors de mes projets d'école pour le plaisir de creer ce jeux. en vue.js full front il y a une database prévue en MySQL pour le futur pour l'instant tout est en front (ce site fonctionne et recoit des améliorations).`,
    textPrivate: `Privé`,
    LikeSite: `lien vers le site web`,
    descriptionTextP5: `Ce jeux est en vue.js pour l'instant en full front-end mais elle obtiendtiendra bientot une base de donnée MySQL avec un backend en golang pour gere la comunication entre le front et la base de donnée. ce dernier est un fan game basé sur l'univers de One Piece qui comport plusieur mode de jeux différents le classique ou l'on doit trouver un personnage précis dans les 250 que contien le json (base de données actuelle en front end) en ce basant sur les information comme la prime, le haki, la taille etc... un autre mode de jeux qui est le fruit du demon ou l'on doit deviner le fruit du démon d'un personnage en se basant sur des indices et un dernier mode de jeux ou l'on doit deviner a quelle personnage appartient quel rire, ce jeux est simple mais amusant et j'ai pris plaisir a le coder. c'est un projet amusant et serieux qui grandi au fur et a mesure des mise a jour et de mes connaissances en dev web.`,

    SecretPageH1: "Vous avez trouvé la page secrète !",

    Score: "Score",
    Level: "Niveau",
    record: "Record",
    InProgress: "En cours...",
    start: "Démarrer",
    resume: "Reprendre",
    pause: "Pause",
    reset: "Recommencer",
    controls: "Contrôles",
    instructions: "Mange les pommes 🍎 pour grandir ! Évite les murs et ton corps !",
  },
  en: {
    titleHome: "Presentation",

    aboutMeTitle: "About Me",
    aboutMeText: `Hello, my name is <strong>Maël LLADO</strong>. I am currently a student at the private school <strong>Ynov Campus Bordeaux</strong>, after obtaining my Professional <strong>Baccalaureate in SN (Digital Systems), RISC option</strong>, with <strong>Highest Honors</strong>, at the Jean-Monnet Polyvalent High School in Libourne.`,
    parcoursTitle: "Background and Experience",
    parcoursText: `Passionate about IT since middle school, I focused my path on programming. During my internships at <strong>Snark Factory</strong>, I discovered web development and learned <strong>HTML, CSS, SCSS</strong>, and <strong>JavaScript</strong> by creating several websites with <strong>Vue.js</strong>.`,
    parcoursTextSeconde: `I also completed other internships in IT maintenance and in specialized stores, which allowed me to broaden my skills.`,
    projetsTitle: "Personal Projects",
    projetsText: `Self-taught, I learned <strong>Python</strong> and developed one of my biggest projects:a <strong>facial recognition</strong> software, presented during my Bac oral exam. This project allowed me to learn how to use <strong>GitHub</strong> and structure my code like a professional developer.`,
    projetsTextSeconde: `I also experimented with <strong>video game programming</strong> using <strong>Unreal Engine 5</strong>, out of curiosity and to expand my knowledge.`,
    objectifsTitle: "Goals",
    objectifsText: `My goal is to continue learning and gaining experience in different areas of IT. I aim to become <strong>versatile</strong>, both in <strong>web development</strong>, <strong>full-stack</strong>, and <strong>video game programming</strong>, which are the subjects that interest me the most.`,
    objectifsTextSeconde: `I also have some initial experience in <strong>cybersecurity</strong>, thanks to my three years in the Bac Pro SN RISC program, my participation in <strong>CTFs</strong>, and my personal research. Curious and motivated, I enjoy taking on new challenges and aspire to pursue an exciting career in software development.`,
    fichiersTitle: "Attached Files",
    fichiersText: `Here you can find my CV and portfolio to learn more about my background and projects.`,
    cvBtn: "My CV",
    portfolioBtn: "My Portfolio",

    titleContact: `Contact`,

    textContact: `Always open to chat, whether it's about professional or personal projects, or job opportunities 👋!`,

    titleProject: `My Projects`,

    titleProjectP1: `Project_Red: Eldoria`,
    textProjectP1: `This project was created as part of my studies at Ynov Campus during my first year (B1). It was developed in one week using Golang. We were asked to create a CLI game, meaning a command-line game to be played directly in the terminal.`,
    titleGithubP1: `Github`,
    textGithubP1: `For this project, we were a team of three, and our work is fully available on GitHub.`,
    descriptionTextP1: `Eldoria is a text-based adventure game where you play as an explorer who discovers the village of Ynovia. Meet Emeryn, the village guide, and uncover the mysteries surrounding this magical place. Discover a portal to another world, but beware of the lurking monsters and the fearsome boss, Maximor! This game runs in the terminal (CLI) but includes a unique feature: an interactive map that makes the gameplay more enjoyable.`,
    textReadMe: `Here’s an excerpt from the Read.me`,
    titleLanguage: `Language`,
    linkTextGithub: `View the Project on GitHub`,

    textProjectP2: `I had 4 weeks to code a software program in Python. I had to create several versions of my code: one for photos, another for videos, and a final one for live video using the webcam.`,
    titleGithubP2: `Personal: GitHub`,
    textGithubP2: `This project is a personal one that I carried out to earn bonus points for my Professional Baccalaureate in Digital Systems (SN), RISC option.`,
    descriptionTextP2: `Our project focuses on facial recognition. We are coding in Python 3 using Visual Studio Code. The goal of our project is to detect faces in a photo or video and compare them to a database containing several faces organized in different folders. The objective is to determine whether the person is known to the database or not. If the face is recognized, the software simply displays the person’s name on the image. This software is interesting because it could be used as part of a security system, in various contexts, or as a ‘doorman’ setup in front of a door or gate. If it recognizes the person, the door or gate unlocks automatically — and vice versa. This makes our project useful and relevant, addressing real-world issues and needs in security.`,

    textProjectP3: `I participated in the CTF 2025 on the Root Me website, organized by the same platform.`,
    titleGithubP3: `SN School`,
    textGithubP3: `This project was assigned by our Digital Systems teacher to train us in cybersecurity and ethical hacking.`,
    descriptionTextP3_1: `CTF Training and Implementation (Programming, Web)`,
    descriptionTextP3_2: `CTF (Capture The Flag) is a national cybersecurity competition where participants compete to solve puzzles and computer security challenges.`,
    descriptionTextP3_3: `The ultimate goal is to 'capture the flag', which is usually a secret code or a specific file hidden within a vulnerable computer system.`,
    descriptionTextP3_4: `CTFs are secure environments that allow cybersecurity professionals and students to learn, practice, and develop their skills while having fun.`,
    textPrivate: `Private`,

    textProjectP5: `One Piece DLE is a fan game project based on the One Piece universe. The goal of the game is to find a specific character from the One Piece world, similar to a GeoGuessr but for characters.`,
    textGithubP5: `This project was created personally outside of my school projects for the enjoyment of creating this game. It is built in Vue.js as a full front-end application, with a planned MySQL database for the future. For now, everything is front-end (this site is functional and continues to receive improvements).`,
    LikeSite: `Link to the website`,
    descriptionTextP5: `This game is built in Vue.js, currently as a full front-end application, but it will soon feature a MySQL database with a Golang backend to manage communication between the front-end and the database. It is a fan game based on the One Piece universe that includes several different game modes: the classic mode where players must find a specific character among the 250 characters contained in the current JSON database (front-end only) based on information such as bounty, haki, height, etc.; another mode called 'Devil Fruit' where players must guess a character's devil fruit based on clues; and a final mode where players must match laughs to their respective characters. This game is simple yet fun to play, and I enjoyed coding it. It is an entertaining and serious project that continues to grow with updates and my increasing knowledge of web development.`,

    SecretPageH1: "You have found the secret page!",
    Score: "Score",
    Level: "Level",
    record: "Record",
    InProgress: "In progress...",
    start: "Start",
    resume: "Resume",
    pause: "break",
    reset: "Reset",
    controls: "Controls",
    instructions: "Eat the apples 🍎 to grow! Avoid the walls and your body!",
  },
};
